
== Introduction

Red Hat Quay is an enterprise-quality registry for building, securing and serving container images. 
It provides secure storage, distribution, and governance of containers and cloud-native artifacts on any infrastructure.

Manual deployments of Red Hat Quay involves a lot of components and the overhead of managing those components. Red Hat Quay is best deployed on Red Hat OpenShift using the Operators which simplifies the deployment and manages all the components.


== Overview

In this hands on lab you will:

* Deploy Red Hat Quay
** Install the OpenShift Data Foundation operator
** Create a NooBaa (MCG) deployment backed by local PVs
** Install the Red Hat Quay Operator
** Create a Red Hat Quay deployment managed by the Operator
* Reconfigure Red Hat Quay
** Restrict non-superuser user creation
** Shorten the server hostname via config editor
** Use a custom certificate for Red Hat Quay
** Enable the new UI preview 
** Enable proxy cache
** Enable storage quota and consumption tracking
* Reconfigure Clair
** Disable the python updater
* Increase the Postgres database size of Quay and Clair
* Increase the size NooBaa’s S3 endpoint
